<a href="https://colab.research.google.com/github/Pradhiksha05/EDA-on-Terrorism-dataset/blob/main/EDA_on_terrorism_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
Terror=pd.read_csv('/content/globalterrorismdb_0718dist.csv', on_bad_lines='skip' , encoding='latin')
pd.set_option("display.max_columns",500)

<ipython-input-4-b206876e3e52>:1: DtypeWarning: Columns (4,31,33,62,76,79,94,96,121) have mixed types. Specify dtype option on import or set low_memory=False.
  Terror=pd.read_csv('/content/globalterrorismdb_0718dist.csv', on_bad_lines='skip' , encoding='latin')

In [5]:
Terror.shape

(18870, 135)

In [6]:
Terror.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region',
       ...
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],
      dtype='object', length=135)

In [7]:
Terror.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,Central America & Caribbean,NaN,Santo Domingo,18.456792,-69.951164,1,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,1,Assassination,NaN,NaN,NaN,NaN,14,Private Citizens & Property,68.0,Named Civilian,NaN,Julio Guzman,58.0,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANO-D,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,North America,Federal,Mexico city,19.371887,-99.086624,1,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,6,Hostage Taking (Kidnapping),NaN,NaN,NaN,NaN,7,Government (Diplomatic),45.0,"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,"Nadine Chaval, daughter",21.0,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23rd of September Communist League,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,NaN,Mexico,1.0,800000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0.0,1.0,1.0,1.0,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,4,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,1,Assassination,NaN,NaN,NaN,NaN,10,Journalists & Media,54.0,Radio Journalist/Staff/Facility,Voice of America,Employee,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,Western Europe,Attica,Athens,37.997490,23.762728,1,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Embassy,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,East Asia,Fukouka,Fukouka,33.580412,130.396361,1,0,NaN,NaN,1,1,1,-9,NaN,NaN,0,1,0,7,Facility/Infrastructure Attack,NaN,NaN,NaN,NaN,7,Government (Diplomatic),46.0,Embassy/Consulate,NaN,U.S. Consulate,217.0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Incendiary,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,-9.0,-9.0,1.0,1.0,NaN

In [8]:
Terror.tail()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,provstate,city,latitude,longitude,specificity,vicinity,location,summary,crit1,crit2,crit3,doubtterr,alternative,alternative_txt,multiple,success,suicide,attacktype1,attacktype1_txt,attacktype2,attacktype2_txt,attacktype3,attacktype3_txt,targtype1,targtype1_txt,targsubtype1,targsubtype1_txt,corp1,target1,natlty1,natlty1_txt,targtype2,targtype2_txt,targsubtype2,targsubtype2_txt,corp2,target2,natlty2,natlty2_txt,targtype3,targtype3_txt,targsubtype3,targsubtype3_txt,corp3,target3,natlty3,natlty3_txt,gname,gsubname,gname2,gsubname2,gname3,gsubname3,motive,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claimmode_txt,claim2,claimmode2,claimmode2_txt,claim3,claimmode3,claimmode3_txt,compclaim,weaptype1,weaptype1_txt,weapsubtype1,weapsubtype1_txt,weaptype2,weaptype2_txt,weapsubtype2,weapsubtype2_txt,weaptype3,weaptype3_txt,weapsubtype3,weapsubtype3_txt,weaptype4,weaptype4_txt,weapsubtype4,weapsubtype4_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propextent_txt,propvalue,propcomment,ishostkid,nhostkid,nhostkidus,nhours,ndays,divert,kidhijcountry,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,ransomnote,hostkidoutcome,hostkidoutcome_txt,nreleased,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
18865,198305240006,1983,5,24,NaN,0,NaN,45,Colombia,3,South America,Santander,Vuelta de Acuna,6.655556,-74.268889,2,0,NaN,NaN,1,1,0,1,1.0,Insurgency/Guerilla Action,0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,4,Military,29.0,Military Unit/Patrol/Convoy,NaN,Military Unit,45.0,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Revolutionary Armed Forces of Colombia (FARC),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,2.0,Automatic or Semi-Automatic Rifle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic firearm,4.0,NaN,NaN,0.0,NaN,NaN,1,4.0,Unknown,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
18866,198305240007,1983,5,24,NaN,0,NaN,45,Colombia,3,South America,Valle del Cauca,Palmira,3.529901,-76.298006,1,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,9,Unknown,NaN,NaN,NaN,NaN,14,Private Citizens & Property,75.0,Village/City/Town/Suburb,NaN,Village of Palmira,45.0,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Revolutionary Armed Forces of Colombia (FARC),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,NaN,Damages: ransacked unknown number of stores an...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
18867,198305240008,1983,5,24,NaN,0,NaN,145,Nicaragua,2,Central America & Caribbean,Chontales,Bartola,12.100000,-85.216667,1,0,NaN,NaN,1,1,0,1,1.0,Insurgency/Guerilla Action,0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,4,Military,29.0,Military Unit/Patrol/Convoy,NaN,Military Unit,145.0,Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Democratic Revolutionary Alliance (ARDE),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,2.0,Automatic or Semi-Automatic Rifle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic firearm,NaN,NaN,0.0,NaN,NaN,0.0,1,4.0,Unknown,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
18868,198305240009,1983,5,24,NaN,0,NaN,145,Nicaragua,2,Central America & Caribbean,Nueva Segovia,Jalapa,13.924030,-86.084980,3,0,NaN,NaN,1,1,0,1,1.0,Insurgency/Guerilla Action,0,1,0,2,Armed Assault,NaN,NaN,NaN,NaN,4,Military,29.0,Military Unit/Patrol/Convoy,NaN,Military Unit,145.0,Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nicaraguan Democratic Force (FDN),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,Firearms,2.0,Automatic or Semi-Automatic Rifle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic firearm,6.0,NaN,NaN,NaN,NaN,NaN,1,4.0,Unknown,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PGIS,0.0,0.0,0.0,0.0,NaN
18869,198305240010,1983,5,24,NaN,0,NaN,603,United Kingdom,8,Western Europe,Northern Ireland,Camlough,54.180640,-6.410521,1,0,NaN,NaN,1,1,1,0,NaN,NaN,0,1,0,3,Bombing/Explosion,NaN,NaN,NaN,NaN,3,Police,23.0,Police Patrol (including vehicles and convoys),NaN,Royal Ulster Constabulary Patrol Car,233.0,Northern Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Irish Republican Army (IRA),NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,Explosives,8.0,Landmine,6.0,Explosives,16.0,Unknown Explosive Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Explosive; Mine,NaN,NaN,NaN,2.0,NaN,NaN,1,3.0,Minor (likely < $1 m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
Terror.info

<bound method DataFrame.info of             eventid  iyear  imonth  iday approxdate  extended resolution  \
0      197000000001   1970       7     2        NaN         0        NaN
1      197000000002   1970       0     0        NaN         0        NaN
2      197001000001   1970       1     0        NaN         0        NaN
3      197001000002   1970       1     0        NaN         0        NaN
4      197001000003   1970       1     0        NaN         0        NaN
...             ...    ...     ...   ...        ...       ...        ...
18865  198305240006   1983       5    24        NaN         0        NaN
18866  198305240007   1983       5    24        NaN         0        NaN
18867  198305240008   1983       5    24        NaN         0        NaN
18868  198305240009   1983       5    24        NaN         0        NaN
18869  198305240010   1983       5    24        NaN         0        NaN

       country         country_txt  region                   region_txt  \
0           58  Dominican Republic       2  Central America & Caribbean
1          130              Mexico       1                North America
2          160         Philippines       5               Southeast Asia
3           78              Greece       8               Western Europe
4          101               Japan       4                    East Asia
...        ...                 ...     ...                          ...
18865       45            Colombia       3                South America
18866       45            Colombia       3                South America
18867      145           Nicaragua       2  Central America & Caribbean
18868      145           Nicaragua       2  Central America & Caribbean
18869      603      United Kingdom       8               Western Europe

              provstate             city   latitude   longitude  specificity  \
0                   NaN    Santo Domingo  18.456792  -69.951164            1
1               Federal      Mexico city  19.371887  -99.086624            1
2                Tarlac          Unknown  15.478598  120.599741            4
3                Attica           Athens  37.997490   23.762728            1
4               Fukouka          Fukouka  33.580412  130.396361            1
...                 ...              ...        ...         ...          ...
18865         Santander  Vuelta de Acuna   6.655556  -74.268889            2
18866   Valle del Cauca          Palmira   3.529901  -76.298006            1
18867         Chontales          Bartola  12.100000  -85.216667            1
18868     Nueva Segovia           Jalapa  13.924030  -86.084980            3
18869  Northern Ireland         Camlough  54.180640   -6.410521            1

       vicinity location summary  crit1  crit2  crit3  doubtterr  alternative  \
0             0      NaN     NaN      1      1      1          0          NaN
1             0      NaN     NaN      1      1      1          0          NaN
2             0      NaN     NaN      1      1      1          0          NaN
3             0      NaN     NaN      1      1      1          0          NaN
4             0      NaN     NaN      1      1      1         -9          NaN
...         ...      ...     ...    ...    ...    ...        ...          ...
18865         0      NaN     NaN      1      1      0          1          1.0
18866         0      NaN     NaN      1      1      1          0          NaN
18867         0      NaN     NaN      1      1      0          1          1.0
18868         0      NaN     NaN      1      1      0          1          1.0
18869         0      NaN     NaN      1      1      1          0          NaN

                  alternative_txt  multiple  success  suicide  attacktype1  \
0                             NaN         0        1        0            1
1                             NaN         0        1        0            6
2                             NaN         0        1        0            1
3                             NaN         0        1        0            3
4                             NaN         0        1        0            7
...                           ...       ...      ...      ...          ...
18865  Insurgency/Guerilla Action         0        1        0            2
18866                         NaN         0        1        0            9
18867  Insurgency/Guerilla Action         0        1        0            2
18868  Insurgency/Guerilla Action         0        1        0            2
18869                         NaN         0        1        0            3

                      attacktype1_txt  attacktype2 attacktype2_txt  \
0                       Assassination          NaN             NaN
1         Hostage Taking (Kidnapping)          NaN             NaN
2                       Assassination          NaN             NaN
3                   Bombing/Explosion          NaN             NaN
4      Facility/Infrastructure Attack          NaN             NaN
...                               ...          ...             ...
18865                   Armed Assault          NaN             NaN
18866                         Unknown          NaN             NaN
18867                   Armed Assault          NaN             NaN
18868                   Armed Assault          NaN             NaN
18869               Bombing/Explosion          NaN             NaN

       attacktype3 attacktype3_txt  targtype1                targtype1_txt  \
0              NaN             NaN         14  Private Citizens & Property
1              NaN             NaN          7      Government (Diplomatic)
2              NaN             NaN         10          Journalists & Media
3              NaN             NaN          7      Government (Diplomatic)
4              NaN             NaN          7      Government (Diplomatic)
...            ...             ...        ...                          ...
18865          NaN             NaN          4                     Military
18866          NaN             NaN         14  Private Citizens & Property
18867          NaN             NaN          4                     Military
18868          NaN             NaN          4                     Military
18869          NaN             NaN          3                       Police

       targsubtype1                                   targsubtype1_txt  \
0              68.0                                     Named Civilian
1              45.0  Diplomatic Personnel (outside of embassy, cons...
2              54.0                    Radio Journalist/Staff/Facility
3              46.0                                  Embassy/Consulate
4              46.0                                  Embassy/Consulate
...             ...                                                ...
18865          29.0                        Military Unit/Patrol/Convoy
18866          75.0                           Village/City/Town/Suburb
18867          29.0                        Military Unit/Patrol/Convoy
18868          29.0                        Military Unit/Patrol/Convoy
18869          23.0     Police Patrol (including vehicles and convoys)

                             corp1                               target1  \
0                              NaN                          Julio Guzman
1      Belgian Ambassador Daughter               Nadine Chaval, daughter
2                 Voice of America                              Employee
3                              NaN                          U.S. Embassy
4                              NaN                        U.S. Consulate
...                            ...                                   ...
18865                          NaN                         Military Unit
18866                          NaN                    Village of Palmira
18867                          NaN                         Military Unit
18868                          NaN                         Military Unit
18869                          NaN  Royal Ulster Constabulary Patrol Car

       natlty1         natlty1_txt  targtype2 targtype2_txt  targsubtype2  \
0         58.0  Dominican Republic        NaN           NaN           NaN
1         21.0             Belgium        NaN           NaN           NaN
2        217.0       United States        NaN           NaN           NaN
3        217.0       United States        NaN           NaN           NaN
4        217.0       United States        NaN           NaN           NaN
...        ...                 ...        ...           ...           ...
18865     45.0            Colombia        NaN           NaN           NaN
18866     45.0            Colombia        NaN           NaN           NaN
18867    145.0           Nicaragua        NaN           NaN           NaN
18868    145.0           Nicaragua        NaN           NaN           NaN
18869    233.0    Northern Ireland        NaN           NaN           NaN

      targsubtype2_txt corp2 target2  natlty2 natlty2_txt  targtype3  \
0                  NaN   NaN     NaN      NaN         NaN        NaN
1                  NaN   NaN     NaN      NaN         NaN        NaN
2                  NaN   NaN     NaN      NaN         NaN        NaN
3                  NaN   NaN     NaN      NaN         NaN        NaN
4                  NaN   NaN     NaN      NaN         NaN        NaN
...                ...   ...     ...      ...         ...        ...
18865              NaN   NaN     NaN      NaN         NaN        NaN
18866              NaN   NaN     NaN      NaN         NaN        NaN
18867              NaN   NaN     NaN      NaN         NaN        NaN
18868              NaN   NaN     NaN      NaN         NaN        NaN
18869              NaN   NaN     NaN      NaN         NaN        NaN

      targtype3_txt  targsubtype3 targsubtype3_txt corp3 target3  natlty3  \
0               NaN           NaN              NaN   NaN     NaN      NaN
1               NaN           NaN              NaN   NaN     NaN      NaN
2               NaN           NaN              NaN   NaN     NaN      NaN
3               NaN           NaN              NaN   NaN     NaN      NaN
4               NaN           NaN              NaN   NaN     NaN      NaN
...             ...           ...              ...   ...     ...      ...
18865           NaN           NaN              NaN   NaN     NaN      NaN
18866           NaN           NaN              NaN   NaN     NaN      NaN
18867           NaN           NaN              NaN   NaN     NaN      NaN
18868           NaN           NaN              NaN   NaN     NaN      NaN
18869           NaN           NaN              NaN   NaN     NaN      NaN

      natlty3_txt                                          gname gsubname  \
0             NaN                                         MANO-D      NaN
1             NaN             23rd of September Communist League      NaN
2             NaN                                        Unknown      NaN
3             NaN                                        Unknown      NaN
4             NaN                                        Unknown      NaN
...           ...                                            ...      ...
18865         NaN  Revolutionary Armed Forces of Colombia (FARC)      NaN
18866         NaN  Revolutionary Armed Forces of Colombia (FARC)      NaN
18867         NaN       Democratic Revolutionary Alliance (ARDE)      NaN
18868         NaN              Nicaraguan Democratic Force (FDN)      NaN
18869         NaN                    Irish Republican Army (IRA)      NaN

      gname2  gsubname2 gname3  gsubname3 motive  guncertain1  guncertain2  \
0        NaN        NaN    NaN        NaN    NaN            0          NaN
1        NaN        NaN    NaN        NaN    NaN            0          NaN
2        NaN        NaN    NaN        NaN    NaN            0          NaN
3        NaN        NaN    NaN        NaN    NaN            0          NaN
4        NaN        NaN    NaN        NaN    NaN            0          NaN
...      ...        ...    ...        ...    ...          ...          ...
18865    NaN        NaN    NaN        NaN    NaN            0          NaN
18866    NaN        NaN    NaN        NaN    NaN            0          NaN
18867    NaN        NaN    NaN        NaN    NaN            0          NaN
18868    NaN        NaN    NaN        NaN    NaN            0          NaN
18869    NaN        NaN    NaN        NaN    NaN            0          NaN

       guncertain3  individual  nperps  nperpcap  claimed  claimmode  \
0              NaN           0     NaN       NaN      NaN        NaN
1              NaN           0     7.0       NaN      NaN        NaN
2              NaN           0     NaN       NaN      NaN        NaN
3              NaN           0     NaN       NaN      NaN        NaN
4              NaN           0     NaN       NaN      NaN        NaN
...            ...         ...     ...       ...      ...        ...
18865          NaN           0     NaN       NaN      NaN        NaN
18866          NaN           0    20.0       NaN      NaN        NaN
18867          NaN           0     NaN       NaN      NaN        NaN
18868          NaN           0     NaN       NaN      NaN        NaN
18869          NaN           0     NaN       NaN      NaN        NaN

      claimmode_txt  claim2  claimmode2 claimmode2_txt  claim3  claimmode3  \
0               NaN     NaN         NaN            NaN     NaN         NaN
1               NaN     NaN         NaN            NaN     NaN         NaN
2               NaN     NaN         NaN            NaN     NaN         NaN
3               NaN     NaN         NaN            NaN     NaN         NaN
4               NaN     NaN         NaN            NaN     NaN         NaN
...             ...     ...         ...            ...     ...         ...
18865           NaN     NaN         NaN            NaN     NaN         NaN
18866           NaN     NaN         NaN            NaN     NaN         NaN
18867           NaN     NaN         NaN            NaN     NaN         NaN
18868           NaN     NaN         NaN            NaN     NaN         NaN
18869           NaN     NaN         NaN            NaN     NaN         NaN

      claimmode3_txt  compclaim  weaptype1 weaptype1_txt  weapsubtype1  \
0                NaN        NaN         13       Unknown           NaN
1                NaN        NaN         13       Unknown           NaN
2                NaN        NaN         13       Unknown           NaN
3                NaN        NaN          6    Explosives          16.0
4                NaN        NaN          8    Incendiary           NaN
...              ...        ...        ...           ...           ...
18865            NaN        NaN          5      Firearms           2.0
18866            NaN        NaN         13       Unknown           NaN
18867            NaN        NaN          5      Firearms           2.0
18868            NaN        NaN          5      Firearms           2.0
18869            NaN        NaN          6    Explosives           8.0

                        weapsubtype1_txt  weaptype2 weaptype2_txt  \
0                                    NaN        NaN           NaN
1                                    NaN        NaN           NaN
2                                    NaN        NaN           NaN
3                 Unknown Explosive Type        NaN           NaN
4                                    NaN        NaN           NaN
...                                  ...        ...           ...
18865  Automatic or Semi-Automatic Rifle        NaN           NaN
18866                                NaN        NaN           NaN
18867  Automatic or Semi-Automatic Rifle        NaN           NaN
18868  Automatic or Semi-Automatic Rifle        NaN           NaN
18869                           Landmine        6.0    Explosives

       weapsubtype2        weapsubtype2_txt  weaptype3 weaptype3_txt  \
0               NaN                     NaN        NaN           NaN
1               NaN                     NaN        NaN           NaN
2               NaN                     NaN        NaN           NaN
3               NaN                     NaN        NaN           NaN
4               NaN                     NaN        NaN           NaN
...             ...                     ...        ...           ...
18865           NaN                     NaN        NaN           NaN
18866           NaN                     NaN        NaN           NaN
18867           NaN                     NaN        NaN           NaN
18868           NaN                     NaN        NaN           NaN
18869          16.0  Unknown Explosive Type        NaN           NaN

       weapsubtype3 weapsubtype3_txt  weaptype4 weaptype4_txt  weapsubtype4  \
0               NaN              NaN        NaN           NaN           NaN
1               NaN              NaN        NaN           NaN           NaN
2               NaN              NaN        NaN           NaN           NaN
3               NaN              NaN        NaN           NaN           NaN
4               NaN              NaN        NaN           NaN           NaN
...             ...              ...        ...           ...           ...
18865           NaN              NaN        NaN           NaN           NaN
18866           NaN              NaN        NaN           NaN           NaN
18867           NaN              NaN        NaN           NaN           NaN
18868           NaN              NaN        NaN           NaN           NaN
18869           NaN              NaN        NaN           NaN           NaN

      weapsubtype4_txt         weapdetail  nkill  nkillus  nkillter  nwound  \
0                  NaN                NaN    1.0      NaN       NaN     0.0
1                  NaN                NaN    0.0      NaN       NaN     0.0
2                  NaN                NaN    1.0      NaN       NaN     0.0
3                  NaN          Explosive    NaN      NaN       NaN     NaN
4                  NaN         Incendiary    NaN      NaN       NaN     NaN
...                ...                ...    ...      ...       ...     ...
18865              NaN  Automatic firearm    4.0      NaN       NaN     0.0
18866              NaN                NaN    0.0      NaN       NaN     0.0
18867              NaN  Automatic firearm    NaN      NaN       0.0     NaN
18868              NaN  Automatic firearm    6.0      NaN       NaN     NaN
18869              NaN    Explosive; Mine    NaN      NaN       NaN     2.0

       nwoundus  nwoundte  property  propextent        propextent_txt  \
0           NaN       NaN         0         NaN                   NaN
1           NaN       NaN         0         NaN                   NaN
2           NaN       NaN         0         NaN                   NaN
3           NaN       NaN         1         NaN                   NaN
4           NaN       NaN         1         NaN                   NaN
...         ...       ...       ...         ...                   ...
18865       NaN       NaN         1         4.0               Unknown
18866       NaN       NaN         1         NaN                   NaN
18867       NaN       0.0         1         4.0               Unknown
18868       NaN       NaN         1         4.0               Unknown
18869       NaN       NaN         1         3.0  Minor (likely < $1 m

       propvalue                                        propcomment  \
0            NaN                                                NaN
1            NaN                                                NaN
2            NaN                                                NaN
3            NaN                                                NaN
4            NaN                                                NaN
...          ...                                                ...
18865        NaN                                                NaN
18866        NaN  Damages: ransacked unknown number of stores an...
18867        NaN                                                NaN

In [11]:
Terror.describe()

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,vicinity,crit1,crit2,crit3,doubtterr,alternative,multiple,success,suicide,attacktype1,attacktype2,attacktype3,targtype1,targsubtype1,natlty1,targtype2,targsubtype2,natlty2,targtype3,targsubtype3,natlty3,gsubname2,gsubname3,guncertain1,guncertain2,guncertain3,individual,nperps,nperpcap,claimed,claimmode,claim2,claimmode2,claim3,claimmode3,compclaim,weaptype1,weapsubtype1,weaptype2,weapsubtype2,weaptype3,weapsubtype3,weaptype4,weapsubtype4,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent,propvalue,ishostkid,nhostkid,nhostkidus,nhours,ndays,ransom,ransomamt,ransomamtus,ransompaid,ransompaidus,hostkidoutcome,nreleased,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
count,1.887000e+04,18870.000000,18870.000000,18870.000000,18870.000000,18870.000000,18870.000000,18123.000000,1.812300e+04,18870.000000,18870.000000,18870.000000,18870.000000,18870.000000,18870.000000,2866.000000,18870.000000,18870.000000,18870.000000,18870.000000,27.000000,2.000000,18870.000000,17809.000000,18815.000000,246.000000,179.000000,218.000000,33.000000,22.000000,33.000000,0.0,0.0,18870.000000,38.000000,2.000000,18870.000000,3731.000000,956.000000,960.000000,250.000000,11.000000,10.000000,1.0,1.0,20.000000,18870.000000,15288.000000,1214.00000,1022.000000,177.000000,153.000000,34.000000,32.00000,15348.000000,1462.000000,1547.000000,13827.000000,1428.000000,1390.000000,18870.000000,8857.000000,4.245000e+03,18701.000000,1625.000000,1625.000000,462.000000,316.000000,18594.000000,4.330000e+02,1.0,9.000000e+01,1.0,670.000000,510.000000,18869.000000,18869.000000,18869.000000,18869.000000
mean,1.978580e+11,1978.517011,6.198781,15.206465,0.019131,177.541176,5.416428,26.370738,-4.786345e+03,1.289401,0.015951,0.989507,0.990991,0.874775,-1.488076,1.226448,0.038580,0.909963,0.000159,3.151298,4.962963,3.000000,7.007419,41.403841,138.008238,9.475610,50.709497,171.224771,8.939394,57.181818,138.151515,NaN,NaN,0.041918,0.342105,0.500000,0.002226,-6.153578,-80.075314,-0.098958,4.516000,0.909091,3.300000,1.0,1.0,0.450000,6.622523,10.485217,6.39374,9.517613,6.299435,7.091503,6.147059,10.46875,1.672335,0.181259,0.398190,1.423158,0.351541,0.064748,0.638209,3.476798,3.315966e+05,0.086894,-15.302769,0.146462,6.424242,24.889241,0.023448,3.788639e+06,20000.0,1.333696e+06,0.0,2.902985,8.225490,-3.631989,-3.589485,0.249987,-2.612963
std,3.406406e+08,3.409654,3.448318,8.955007,0.136989,166.162416,3.357730,22.515713,6.402079e+05,0.952265,0.125290,0.101898,0.094490,0.330983,3.563100,0.524458,0.192596,0.286242,0.012608,1.988080,2.441334,1.414214,6.288196,30.803331,77.891122,6.736242,27.938425,99.959392,6.072167,25.531747,71.290831,NaN,NaN,0.200408,0.480783,0.707107,0.047127,73.539927,39.465865,1.859395,3.081514,0.301511,3.560587,NaN,NaN,0.510418,2.414232,7.153544,1.93501,6.962273,2.237503,6.704633,1.282336,7.50047,7.496595,1.086589,2.556315,10.227504,2.294921,0.362152,0.803665,0.527205,8.718273e+06,0.281687,125.510934,4.552995,81.303740,64.893591,0.151327,4.845468e+07,NaN,4.800603e+06,NaN,1.298898,28.655294,4.529369,4.575088,0.645339,4.518743
min,1.970000e+11,1970.000000,0.000000,0.000000,0.000000,4.000000,1.000000,-45.867889,-8.618590e+07,1.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,2.000000,1.000000,1.000000,4.000000,1.000000,1.000000,11.000000,1.000000,8.000000,15.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-9.000000,1.000000,0.000000,1.000000,1.0,1.0,0.000000,1.000000,1.000000,2.00000,2.000000,5.000000,2.000000,5.000000,2.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000,2.000000,-9.900000e+01,0.000000,-99.000000,-99.000000,-99.000000,0.000000,0.000000,0.000000e+00,20000.0,0.000000e+00,0.0,2.000000,-99.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,1.977042e+11,1977.000000,3.000000,8.000000,0.000000,69.000000,2.000000,13.692880,-8.688120e+01,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,2.000000,2.500000,2.000000,18.000000,69.000000,3.000000,25.000000,94.000000,3.000000,39.750000,83.000000,NaN,NaN,0.000000,0.000000,0.250000,0.000000,1.000000,-99.000000,0.000000,2.000000,1.000000,1.250000,1.0,1.0,0.000000,5.000000,3.000000,5.00000,3.000000,5.000000,3.000000,5.000000,2.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,2.000000e+03,0.000000,-99.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,20000.0,0.000000e+00,0.0,2.000000,1.000000,-9.000000,-9.000000,0.000000,-9.000000
50%,1.979101e+11,1979.000000,6.000000,15.000000,0.000000,110.000000,5.000000,33.888523,-6.926293e+00,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,3.000000,4.000000,29.000000,111.000000,8.000000,61.000000,212.500000,7.000000,64.500000,110.000000,NaN,NaN,0.000000,0.000000,0.500000,0.000000,3.000000,-99.000000,0.000000,5.000000,1.000000,2.000000,1.0,1.0,0.000000,6.000000,15.000000,6.00000,7.000000,5.000000,3.000000,6.000000,11.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,1.000000e+04,0.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000e+00,20000.0,7.750000e+04,0.0,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1.981082e+11,1981.000000,9.000000,23.000000,0.000000,209.000000,8.000000,43.184180,9.174508e+00,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,7.000000,3.500000,14.000000,69.000000,216.000000,14.000000,69.000000,217.000000,14.000000,77.000000,216.000000,NaN,NaN,0.000000,1.000000,0.750000,0.000000,5.000000,-99.000000,1.000000,5.000000,1.000000,2.000000,1.0,1.0,1.000000,6.000000,16.000000,6.00000,16.000000,6.000000,11.000000,6.000000,16.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,4.500000e+04,0.000000,2.000000,0.000000,0.000000,20.000000,0.000000,4.350000e+05,20000.0,7.750000e+05,0.0,4.000000,2.000000,0.000000,0.000000,1.000000,1.000000
max,1.983052e+11,1986.000000,12.000000,31.000000,1.000000,605.000000,12.000000,64.837778,1.726362e+02,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,9.000000,7.000000,4.000000,22.000000,113.000000,999.000000,22.000000,108.000000,999.000000,22.000000,108.000000,233.000000,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1200.000000,26.000000,1.000000,10.000000,1.000000,10.000000,1.0,1.0,1.000000,13.000000,31.000000,13.00000,28.000000,13.000000,28.000000,9.000000,27.00000,422.000000,30.000000,85.000000,700.000000,50.000000,5.000000,1.000000,4.000000,5.480000e+08,1.000000,4000.000000,70.000000,999.000000,752.000000,1.000000,1.000000e+09,20000.0,4.100000e+07,0.0,7.000000,215.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
Terror.isnull().sum()

eventid           0
iyear             0
imonth            0
iday              0
approxdate    18849
              ...
INT_LOG           1
INT_IDEO          1
INT_MISC          1
INT_ANY           1
related       18143
Length: 135, dtype: int64

In [13]:
Terror.dropna(inplace=True)

In [14]:
Terror.isnull().sum()

eventid       0.0
iyear         0.0
imonth        0.0
iday          0.0
approxdate    0.0
             ...
INT_LOG       0.0
INT_IDEO      0.0
INT_MISC      0.0
INT_ANY       0.0
related       0.0
Length: 135, dtype: float64

In [15]:
Terror.duplicated()

Series([], dtype: bool)